version: '2'
services:
 o2o-ddk-wechat:
   build: .
   image: registry.vcredit.com/o2o/wld-wechat-client
   ports:
   - 3200:80
   environment:
    NODE_ENV: development
   container_name: wld-wechat-client
   mem_limit: 2048M
